USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/wender/alcatelc7/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
DEVICE_RESOLUTION := 480x854
BOARD_HAS_NO_SELECT_BUTTON := true
USE_OPENGL_RENDERER := true
TARGET_BOOTLOADER_BOARD_NAME := mt6582

# Partitions
# make_ext4fs requires numbers in dec format
BOARD_BOOTIMAGE_PARTITION_SIZE := 6291456
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := next number is fake just to complile real nunber is 6291456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 7000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 642777088
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
#BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00380000
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00480000
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x08c60000
#BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
#BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/wender/alcatelc7/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
